### ISSUE TITLE
mq import replace not replacing the %s correctly.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [Josh5/mq-cli#8]
```
[mq]
patch_naming = ISSUE_%s
```

Provide a name for this patch: 454
ISSUE_%_project.hg

When I would expect

ISSUE_454_project.hg

**Comment by LiamKarlMitchell** [comment]
Appears as if the ini_parser it is not reading the % symbol.

In this part.
```
gsub(/^[ \s]+|[ \s]+$/, "", $2)
```
I don't know awk/gsub sadly, but maybe the \s is not needed it works when I remove.

Suggest to use hg config.
```bash
PATCH_NAMING=$(hg config mq.patch_naming)
PATCH_NAMING=${PATCH_NAMING:-%s_%s}

#Which lets us replace like this with printf
selected_patch=$(printf "$PATCH_NAMING" "$name" "$project");
```

Or to fix ini parser.

**Comment by Josh5** [comment]
I wanted this fixed fast so i've added the following 2 commits
31dc3214b3ce16de6c3dee97ef7798c18e7be5d9
d23688c37e922b53caa2be3aa76bd601f885c5fd
